twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@TalesFromADevFlowbite/form/default.html.twig'
    globals:
        app_name: 'Ma super app'

when@test:
    twig:
        strict_variables: true
